services:
  - type: web
    name: mr-test-generator
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: GITLAB_URL
        value: https://biosphere.teamsystem.com/
      - key: GITLAB_USERNAME
        value: e.zefaj
      - key: ANTHROPIC_API_KEY
        sync: false
